AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/spring.rb'
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 100
Metrics/LineLength:
  Max: 160
Documentation:
  Enabled: false
